### ISSUE TITLE
Service No Longer Returns Active Streams

### ISSUE THREAD

**Issue by patrickjquinn** [PaquitoSoft/goear-api#5]
When the API returns a stream url it seems to be a recording of a default "Sorry this is unavailable" message in Spanish (You Know I Don't Speak Spanish, Baxter) instead of the actual song's url. Seems they have made some anti scarping changes....

**Comment by PaquitoSoft** [comment]
Hi @patrickjquinn,
I've being running some tests and it seems that you need to pass a *Referer* mandatory header in the request for the stream URL.
If you set it, for example, to _http://www.goear.com/_ it works.

The kind of stream URLs returned does not point to the actual song file. Instead, you receive a redirect with the actual file URL.
If you don't use the mandatory header, you get a redirect to a default audio track which says you must go to their website to listen to the song.

I think there are (at least) two options:
* I can add a note to the documentation about the new mandatory header when requesting the stream file.
* I can enhance the library so it returns the actual song file URL. This will make the *search* api method slower, as it would have to make a request for every returned result to get the actual song URL. Also, maybe they'll block a bunch of concurrent or consecutive requests.

I'll run some tests on the second option in order to get more info about what path to follow.

In the meantime, I wait for your comments/suggestons.

**Comment by voxsoftware** [comment]
Utilicen mi fork de esta librería vw-goear-api
My fork it's working: npm install vw-goear-api




2016-02-24 11:59 GMT-05:00 PaquitoSoft <notifications@github.com>:

**Comment by PaquitoSoft** [comment]
Estimado @voxsoftware,
Su fork de mi módulo falla de igual modo que el original puesto que los cambios que usted implementó sobre el mismo no gestionan en absoluto la problemática expuesta por @patrickjquinn.
No creo que los comentarios sobre las peticiones abiertas sobre mi módulo sean el mejor sitio para publicitar el suyo.
Reciba un cordial saludo.

Dear @voxsoftware,
Your fork fails the same this one does because the changes you've implemented does not manage the problems explained by @patrickjquinn at all.
I don't think comments on this module's issues is the best place to advertise yours.
Regards.

**Comment by voxsoftware** [comment]
Add a referer header, to solve the problem. Work for me. I have an
application that download from goear.

2016-02-24 14:48 GMT-05:00 PaquitoSoft <notifications@github.com>:

**Comment by PaquitoSoft** [comment]
@patrickjquinn 
As there is now way to directly translate the track URL to the actual file URL, it would be needed to make a single request to GoEar for each result.
I run some tests and that process adds too much time to every search (more than 20 seconds), so I decided to add a note in the documentation about the mandatory _Referer_ header when using the tracks Urls. I also extended one of the tests to check this behavior is valid.

Regards.
